--INSERT INTO PRODUCTO SET (`UUID`, `NOMBRE`, `SKU`, `DESCRIPTION`, `PRECIO`, `TIPO_PRODUCTO`)
--VALUES('d1d3bf08-e9cf-40', 'MARTILLO', '123', 'SE UTILIZA PARA PONER CLAVOS', 15000, NULL)
--
--INSERT INTO PRODUCTO SET (`UUID`, `NOMBRE`, `SKU`, `DESCRIPTION`, `PRECIO`, `TIPO_PRODUCTO`)
--VALUES('6873a595-bb5e-4b', 'PALA', '123', 'SE UTILIZA PARA EXCAVAR', 20000, NULL)
--
--INSERT INTO PRODUCTO SET (`UUID`, `NOMBRE`, `SKU`, `DESCRIPTION`, `PRECIO`, `TIPO_PRODUCTO`)
--VALUES('492084e9-e4a9-4a',, 'CEMENTO', '123', 'MULTIPLES USOS', 50000, NULL)
--
--INSERT INTO PRODUCTO SET (`UUID`, `NOMBRE`, `SKU`, `DESCRIPTION`, `PRECIO`, `TIPO_PRODUCTO`)
--VALUES('001fd7e9-8a1a-48', 'TALADRO', '123', 'MULTIPLES USOS', 150000, NULL)

select * from PRODUCTO;
